### ISSUE TITLE
Use python logging instead of print statements to give game status information.

### ISSUE THREAD

**Issue by BasilBibi** [billlanyon/TTT#34]
Definition Of Done

A developer should be able to set logging level from command line to see debug information.

Should be able to divert logging messages to a log file.

Manual testing should be sufficient at this stage.

**Comment by billlanyon** [comment]
I have pushed a version to the TTT34 branch that seems to pass my manual testing: see attache files.
But I my code using argparse seems to have blown up  the command line for running the pytests like this: 'python -m pytest -v', yet they do seem to run when launched 'python -m pytest'... and I have yet to figure out why.

![ConsoleDebugMessage](https://user-images.githubusercontent.com/12585911/87923544-f3e7d100-ca7d-11ea-93ff-619ecf0f512e.png)

[ttt.log](https://github.com/billlanyon/TTT/files/4946811/ttt.log)

**Comment by billlanyon** [comment]
Argparse removed and logging started from config file instead.
